import type { IconType } from "react-icons";
import { Code2 } from "lucide-react";
import {
  SiAngular,
  SiAstro,
  SiBootstrap,
  SiCss,
  SiDart,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiExpress,
  SiFastapi,
  SiFigma,
  SiFirebase,
  SiFlask,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGo,
  SiGooglecloud,
  SiGraphql,
  SiHtml5,
  SiJavascript,
  SiJenkins,
  SiJest,
  SiKotlin,
  SiKubernetes,
  SiLaravel,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNetlify,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiOpenjdk,
  SiPhp,
  SiPostgresql,
  SiPrisma,
  SiPython,
  SiReact,
  SiRedis,
  SiRedux,
  SiRuby,
  SiRubyonrails,
  SiRust,
  SiSass,
  SiScala,
  SiSharp,
  SiSolid,
  SiSpring,
  SiSqlite,
  SiSupabase,
  SiSvelte,
  SiSwift,
  SiTailwindcss,
  SiTanstack,
  SiTerraform,
  SiTypescript,
  SiVercel,
  SiVite,
  SiVitest,
  SiVuedotjs,
  SiWebpack,
} from "react-icons/si";

export type TechOption = { name: string; icon: IconType };

/** Curated so the admin picks from known names instead of free-typing typos. */
export const TECH_STACK_OPTIONS: TechOption[] = [
  { name: "JavaScript", icon: SiJavascript },
  { name: "TypeScript", icon: SiTypescript },
  { name: "Python", icon: SiPython },
  { name: "Java", icon: SiOpenjdk },
  { name: "C#", icon: SiSharp },
  { name: "C++", icon: Code2 },
  { name: "Go", icon: SiGo },
  { name: "Rust", icon: SiRust },
  { name: "PHP", icon: SiPhp },
  { name: "Ruby", icon: SiRuby },
  { name: "Kotlin", icon: SiKotlin },
  { name: "Swift", icon: SiSwift },
  { name: "Dart", icon: SiDart },
  { name: "Scala", icon: SiScala },
  { name: "React", icon: SiReact },
  { name: "Next.js", icon: SiNextdotjs },
  { name: "Vue.js", icon: SiVuedotjs },
  { name: "Angular", icon: SiAngular },
  { name: "Svelte", icon: SiSvelte },
  { name: "Solid.js", icon: SiSolid },
  { name: "Astro", icon: SiAstro },
  { name: "Node.js", icon: SiNodedotjs },
  { name: "Express", icon: SiExpress },
  { name: "NestJS", icon: SiNestjs },
  { name: "Django", icon: SiDjango },
  { name: "Flask", icon: SiFlask },
  { name: "FastAPI", icon: SiFastapi },
  { name: "Spring", icon: SiSpring },
  { name: "Laravel", icon: SiLaravel },
  { name: "Ruby on Rails", icon: SiRubyonrails },
  { name: ".NET", icon: SiDotnet },
  { name: "PostgreSQL", icon: SiPostgresql },
  { name: "MySQL", icon: SiMysql },
  { name: "MongoDB", icon: SiMongodb },
  { name: "Redis", icon: SiRedis },
  { name: "SQLite", icon: SiSqlite },
  { name: "Supabase", icon: SiSupabase },
  { name: "Firebase", icon: SiFirebase },
  { name: "Prisma", icon: SiPrisma },
  { name: "GraphQL", icon: SiGraphql },
  { name: "Docker", icon: SiDocker },
  { name: "Kubernetes", icon: SiKubernetes },
  { name: "AWS", icon: Code2 },
  { name: "Azure", icon: Code2 },
  { name: "Google Cloud", icon: SiGooglecloud },
  { name: "Vercel", icon: SiVercel },
  { name: "Netlify", icon: SiNetlify },
  { name: "Terraform", icon: SiTerraform },
  { name: "Nginx", icon: SiNginx },
  { name: "Linux", icon: SiLinux },
  { name: "Git", icon: SiGit },
  { name: "GitHub", icon: SiGithub },
  { name: "GitHub Actions", icon: SiGithubactions },
  { name: "Jenkins", icon: SiJenkins },
  { name: "Tailwind CSS", icon: SiTailwindcss },
  { name: "CSS3", icon: SiCss },
  { name: "HTML5", icon: SiHtml5 },
  { name: "Sass", icon: SiSass },
  { name: "Bootstrap", icon: SiBootstrap },
  { name: "Figma", icon: SiFigma },
  { name: "Vite", icon: SiVite },
  { name: "Webpack", icon: SiWebpack },
  { name: "Jest", icon: SiJest },
  { name: "Vitest", icon: SiVitest },
  { name: "Playwright", icon: Code2 },
  { name: "TanStack Query", icon: SiTanstack },
  { name: "Redux", icon: SiRedux },
];

const TECH_ICON_MAP = new Map(TECH_STACK_OPTIONS.map((option) => [option.name, option.icon]));

/** Falls back to a generic icon for stack entries saved before this list existed. */
export function getTechIcon(name: string): IconType {
  return TECH_ICON_MAP.get(name) ?? Code2;
}
